### ISSUE TITLE
DisplayPort on RX 570?

### ISSUE THREAD

**Issue by swordsx48** [joostiphone/Z390-Hackintosh-Joost#1]
Hey, how did you get the DisplayPort working on the 570?It works for me on High Sierra and Mojave but not Big Sur. I've tried adgpmod=pikera

**Comment by swordsx48** [comment]
Oh and the craziest thing is that the apple logo for boot stage 1 shows on it..

**Comment by joostiphone** [comment]
I'm pretty sure it worked out of the box. Do you have the latest kexts installed? My boot arguments are: slide=0 keepsyms=1 dart=0 debug=0x100 agdpmod=pikera alcid=11 shikigva=80 igfxfw=2

I'm no expert here, but let me know if that works. If you have the same system as I have, then you can use my uploaded EFI and copy your own serials numbers etc. using OpenCore Configurator.
